export const dataLKInput = {
  message: "Success!",
  op_id: "1606",
  pack_id: 194,
  pack_table: "IWAKI_PACK",
  op_table: "2406_OP",
  prioriti: "0",
  e1_user: "7",
  e2_user: "8",
  e1_date: "2024-06-14 08:35:38.920000",
  e2_date: "2024-06-14 08:36:27.533000",
  e1_qa: "",
  e2_qa: "2",
  is_qa: null,
  image_exits: "5",
  Input_e1: [
    {
      No: "14.1",
      field_name: "真空度",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "14.2",
      field_name: "真空度",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "14.3",
      field_name: "真空度",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "14.4",
      field_name: "真空度",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "14.5",
      field_name: "真空度",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "15.1",
      field_name: "振動・騒音",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "15.2",
      field_name: "振動・騒音",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "15.3",
      field_name: "振動・騒音",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "15.4",
      field_name: "振動・騒音",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "15.5",
      field_name: "振動・騒音",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "16.1",
      field_name: "作業確認",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "16.2",
      field_name: "作業確認",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "16.3",
      field_name: "作業確認",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "16.4",
      field_name: "作業確認",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "16.5",
      field_name: "作業確認",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "5",
    },
    {
      No: "17.1",
      field_name: "耐水圧検査",
      sheet_name: "Checksheet",
      hotkeys: "✔:1",
      mark: "",
      result: "5",
    },
    {
      No: "17.2",
      field_name: "耐水圧検査",
      sheet_name: "Checksheet",
      hotkeys: "✔:1",
      mark: "",
      result: "5",
    },
    {
      No: "17.3",
      field_name: "耐水圧検査",
      sheet_name: "Checksheet",
      hotkeys: "✔:1",
      mark: "",
      result: "5",
    },
    {
      No: "17.4",
      field_name: "耐水圧検査",
      sheet_name: "Checksheet",
      hotkeys: "✔:1",
      mark: "",
      result: "5",
    },
    {
      No: "17.5",
      field_name: "耐水圧検査",
      sheet_name: "Checksheet",
      hotkeys: "✔:1",
      mark: "",
      result: "5",
    },
  ],
  Input_e2: [
    {
      No: "14.1",
      field_name: "真空度",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "14.2",
      field_name: "真空度",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "14.3",
      field_name: "真空度",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "14.4",
      field_name: "真空度",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "14.5",
      field_name: "真空度",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "15.1",
      field_name: "振動・騒音",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "15.2",
      field_name: "振動・騒音",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "15.3",
      field_name: "振動・騒音",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "15.4",
      field_name: "振動・騒音",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "15.5",
      field_name: "振動・騒音",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "16.1",
      field_name: "作業確認",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "16.2",
      field_name: "作業確認",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "16.3",
      field_name: "作業確認",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "16.4",
      field_name: "作業確認",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "16.5",
      field_name: "作業確認",
      sheet_name: "Checksheet",
      hotkeys: "レ：1",
      mark: "",
      result: "6",
    },
    {
      No: "17.1",
      field_name: "耐水圧検査",
      sheet_name: "Checksheet",
      hotkeys: "✔:1",
      mark: "",
      result: "6",
    },
    {
      No: "17.2",
      field_name: "耐水圧検査",
      sheet_name: "Checksheet",
      hotkeys: "✔:1",
      mark: "",
      result: "6",
    },
    {
      No: "17.3",
      field_name: "耐水圧検査",
      sheet_name: "Checksheet",
      hotkeys: "✔:1",
      mark: "",
      result: "6",
    },
    {
      No: "17.4",
      field_name: "耐水圧検査",
      sheet_name: "Checksheet",
      hotkeys: "✔:1",
      mark: "",
      result: "6",
    },
    {
      No: "17.5",
      field_name: "耐水圧検査",
      sheet_name: "Checksheet",
      hotkeys: "✔:1",
      mark: "",
      result: "6",
    },
  ],
  Grid_e1: [],
  Grid_e2: [],
  path_files: [
    ["/Files/2406/240614_083503941138_MDG_1_240614_083503943137_MDG_1.JPG"],
  ],
  path_thumbs: [
    ["/Thumbnail/2406/240614_083503941138_MDG_1_240614_083503943137_MDG_1.JPG"],
  ],
};

export const dataLK = {
  message: "Success!",
  op_id: "1607",
  pack_id: 194,
  pack_table: "IWAKI_PACK",
  op_table: "2406_OP",
  prioriti: "0",
  e1_user: "7",
  e2_user: "8",
  e1_date: "2024-06-14 08:35:48.383000",
  e2_date: "2024-06-14 08:36:34.400000",
  e1_qa: "",
  e2_qa: "5",
  is_qa: null,
  image_exits: "5",
  Input_e1: [
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "6",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "6",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "6",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "6",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "6",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "6",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "6",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "6",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "6",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "6",
    },
  ],
  Input_e2: [
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "1",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "1",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "1",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "1",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "1",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "1",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "1",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "1",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "1",
    },
    {
      No: "1",
      field_name: "機種名",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "Model",
      result: "1",
    },
  ],
  Grid_e1: [
    {
      No: "",
      field_name: "MFG　No.（製造番号)",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "MFG",
      result: "1234",
    },
  ],
  Grid_e2: [
    {
      No: "",
      field_name: "MFG　No.（製造番号)",
      sheet_name: "Name plate",
      hotkeys: "",
      mark: "MFG",
      result: "345†678†123†765†789",
    },
  ],
  path_files: [
    ["/Files/2406/240614_083503941138_MDG_1_240614_083503943137_MDG_1.JPG"],
  ],
  path_thumbs: [
    ["/Thumbnail/2406/240614_083503941138_MDG_1_240614_083503943137_MDG_1.JPG"],
  ],
};
