name: "sonar_cloud_scan_github_actions"
on:
  push:        # Tự động kích hoạt khi có push code lên repository
    branches:
      - main 
  workflow_dispatch:
  schedule:
    - cron: "0,30 0-15 * * *"
  watch:
    types: [started]

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
              -Dsonar.organization=rs-dri-0
              -Dsonar.projectKey=RS-DRI-0_iwaki_rs
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
